export const hiraganaRows = {
  "Row 1 (a-i-u-e-o)": [
    { char: "あ", romaji: "a" },
    { char: "い", romaji: "i" },
    { char: "う", romaji: "u" },
    { char: "え", romaji: "e" },
    { char: "お", romaji: "o" },
  ],
  "Row 2 (ka-ki-ku-ke-ko)": [
    { char: "か", romaji: "ka" },
    { char: "き", romaji: "ki" },
    { char: "く", romaji: "ku" },
    { char: "け", romaji: "ke" },
    { char: "こ", romaji: "ko" },
  ],
  "Row 3 (ga-gi-gu-ge-go) [Dakuon]": [
    { char: "が", romaji: "ga" },
    { char: "ぎ", romaji: "gi" },
    { char: "ぐ", romaji: "gu" },
    { char: "げ", romaji: "ge" },
    { char: "ご", romaji: "go" },
  ],
  "Row 4 (sa-shi-su-se-so)": [
    { char: "さ", romaji: "sa" },
    { char: "し", romaji: "shi" },
    { char: "す", romaji: "su" },
    { char: "せ", romaji: "se" },
    { char: "そ", romaji: "so" },
  ],
  "Row 5 (za-ji-zu-ze-zo) [Dakuon]": [
    { char: "ざ", romaji: "za" },
    { char: "じ", romaji: "ji" },
    { char: "ず", romaji: "zu" },
    { char: "ぜ", romaji: "ze" },
    { char: "ぞ", romaji: "zo" },
  ],
  "Row 6 (ta-chi-tsu-te-to)": [
    { char: "た", romaji: "ta" },
    { char: "ち", romaji: "chi" },
    { char: "つ", romaji: "tsu" },
    { char: "て", romaji: "te" },
    { char: "と", romaji: "to" },
  ],
  "Row 7 (da-ji-zu-de-do) [Dakuon]": [
    { char: "だ", romaji: "da" },
    { char: "ぢ", romaji: "ji" },
    { char: "づ", romaji: "zu" },
    { char: "で", romaji: "de" },
    { char: "ど", romaji: "do" },
  ],
  "Row 8 (na-ni-nu-ne-no)": [
    { char: "な", romaji: "na" },
    { char: "に", romaji: "ni" },
    { char: "ぬ", romaji: "nu" },
    { char: "ね", romaji: "ne" },
    { char: "の", romaji: "no" },
  ],
  "Row 9 (ha-hi-fu-he-ho)": [
    { char: "は", romaji: "ha" },
    { char: "ひ", romaji: "hi" },
    { char: "ふ", romaji: "fu" },
    { char: "へ", romaji: "he" },
    { char: "ほ", romaji: "ho" },
  ],
  "Row 10 (ba-bi-bu-be-bo) [Dakuon]": [
    { char: "ば", romaji: "ba" },
    { char: "び", romaji: "bi" },
    { char: "ぶ", romaji: "bu" },
    { char: "べ", romaji: "be" },
    { char: "ぼ", romaji: "bo" },
  ],
  "Row 11 (pa-pi-pu-pe-po) [Handakuon]": [
    { char: "ぱ", romaji: "pa" },
    { char: "ぴ", romaji: "pi" },
    { char: "ぷ", romaji: "pu" },
    { char: "ぺ", romaji: "pe" },
    { char: "ぽ", romaji: "po" },
  ],
  "Row 12 (ma-mi-mu-me-mo)": [
    { char: "ま", romaji: "ma" },
    { char: "み", romaji: "mi" },
    { char: "む", romaji: "mu" },
    { char: "め", romaji: "me" },
    { char: "も", romaji: "mo" },
  ],
  "Row 13 (ya-yu-yo)": [
    { char: "や", romaji: "ya" },
    { char: "ゆ", romaji: "yu" },
    { char: "よ", romaji: "yo" },
  ],
  "Row 14 (ra-ri-ru-re-ro)": [
    { char: "ら", romaji: "ra" },
    { char: "り", romaji: "ri" },
    { char: "る", romaji: "ru" },
    { char: "れ", romaji: "re" },
    { char: "ろ", romaji: "ro" },
  ],
  "Row 15 (wa-wo-n)": [
    { char: "わ", romaji: "wa" },
    { char: "を", romaji: "wo" },
    { char: "ん", romaji: "n" },
  ],
  "Row 16 (Kya-Kyu-Kyo) [Yōon]": [
    { char: "きゃ", romaji: "kya" },
    { char: "きゅ", romaji: "kyu" },
    { char: "きょ", romaji: "kyo" },
  ],
  "Row 17 (Gya-Gyu-Gyo) [Yōon]": [
    { char: "ぎゃ", romaji: "gya" },
    { char: "ぎゅ", romaji: "gyu" },
    { char: "ぎょ", romaji: "gyo" },
  ],
  "Row 18 (Sha-Shu-Sho) [Yōon]": [
    { char: "しゃ", romaji: "sha" },
    { char: "しゅ", romaji: "shu" },
    { char: "しょ", romaji: "sho" },
  ],
  "Row 19 (Ja-Ju-Jo) [Yōon]": [
    { char: "じゃ", romaji: "ja" },
    { char: "じゅ", romaji: "ju" },
    { char: "じょ", romaji: "jo" },
  ],
  "Row 20 (Cha-Chu-Cho) [Yōon]": [
    { char: "ちゃ", romaji: "cha" },
    { char: "ちゅ", romaji: "chu" },
    { char: "ちょ", romaji: "cho" },
  ],
  "Row 21 (Nya-Nyu-Nyo) [Yōon]": [
    { char: "にゃ", romaji: "nya" },
    { char: "にゅ", romaji: "nyu" },
    { char: "にょ", romaji: "nyo" },
  ],
  "Row 22 (Hya-Hyu-Hyo) [Yōon]": [
    { char: "ひゃ", romaji: "hya" },
    { char: "ひゅ", romaji: "hyu" },
    { char: "ひょ", romaji: "hyo" },
  ],
  "Row 23 (Bya-Byu-Byo) [Yōon]": [
    { char: "びゃ", romaji: "bya" },
    { char: "びゅ", romaji: "byu" },
    { char: "びょ", romaji: "byo" },
  ],
  "Row 24 (Pya-Pyu-Pyo) [Yōon]": [
    { char: "ぴゃ", romaji: "pya" },
    { char: "ぴゅ", romaji: "pyu" },
    { char: "ぴょ", romaji: "pyo" },
  ],
};
